title =  "Association Communautaire Cardinal Creek Community Association"
baseURL = "http://hugo.cardinalcreek.org/"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
copyright = "Association Communautaire Cardinal Creek Community Association"

SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

#languages:
#  en:
#    title: Cardinal Creek Community Association
#    weight: 1
#  fr:
#    title: Association Communautaire Cardinal Creek
#    weight: 2

[params]
  favicon = ""
  site_logo = "/images/ccca_horizontal_logo_880x140.svg"
  description = "Building an even better community... together!"
  facebook = "https://www.facebook.com/groups/395044333916294"
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "" #bg-black"
  featured_image = "/images/ccca_horizontal_logo_880x140.svg"
  recent_posts_number = 10
  permalinks = "/:year/:month/:title/"
  omit_header_text = true
#  custom_css = "static/main.css"

  [params.navigation]
    help = "Help"

[languages]
  [languages.en]
    title = "Cardinal Creek Community Association"
    weight = 1
    [languages.en.params]
      linkedin = ""
  [languages.fr]
    title = "Association Communautaire Cardinal Creek"
    weight = 2
    [languages.fr.params]
      linkedin = ""
      [languages.fr.params.navigation]
        help = "Aide"

